## HomeMessage - Slot Management System

This document covers the two-table slot architecture and booking rules.

---

### Architecture Overview

The slot system uses **two tables**:

| Table | Purpose | Key Fields |
|-------|---------|------------|
| `slots` | Time templates (reusable) | start_time, end_time, sort_order, is_active |
| `master_slot_bookings` | Status per master+slot+date | master_id, slot_id, date, status, order_id |

**Why two tables?**
- Slots (time windows) are templates: 09:00-10:00, 10:30-11:30, etc.
- Each master has their own booking status per slot per day
- Easy to manage: add/remove time slots without affecting existing bookings

---

### Slot Templates (slots table)

```php
// Default slots generated by SlotService::generateDefaultSlots()
09:00 - 10:00  (1 hour session)
10:30 - 11:30  (30 min gap)
12:00 - 13:00
13:30 - 14:30
15:00 - 16:00
16:30 - 17:30
18:00 - 19:00
19:30 - 20:30
```

**Business Rules:**
- Each slot is 1 hour
- 30 minute gap between slots
- Slots are shared across all masters (templates only)
- Admin can add/edit/delete slot templates
- Changes don't affect existing bookings

---

### Booking Statuses (master_slot_bookings table)

| Status | Code | Bookable | Display | Description |
|--------|------|----------|---------|-------------|
| Free | `FREE` | Yes | Bo'sh | Available for booking (implicit - no row exists) |
| Pending | `PENDING` | No | Kutilmoqda | Order created, awaiting confirmation |
| Reserved | `RESERVED` | No | Band | Paid and confirmed |
| Blocked | `BLOCKED` | No | Yopiq | Manually blocked by admin |

---

### Status Transitions

```
┌─────────────────────────────────────────────────────────┐
│                     SLOT LIFECYCLE                       │
└─────────────────────────────────────────────────────────┘

                    ┌──────────┐
         ┌─────────→│   FREE   │←─────────┐
         │          │ (no row) │          │
         │          └────┬─────┘          │
         │               │                │
    Cancel/NoAnswer      │ Order Created  │ Admin Unblock
         │               ▼                │
         │          ┌──────────┐          │
         └──────────│ PENDING  │──────────┘
                    └────┬─────┘
                         │
                         │ Payment Confirmed
                         ▼
                    ┌──────────┐
                    │ RESERVED │
                    └──────────┘


                    ┌──────────┐
      Admin Block → │ BLOCKED  │ ← Can block FREE/no-row only
                    └──────────┘   Cannot block RESERVED
```

---

### Database Schema

```php
// slots (time templates)
Schema::create('slots', function (Blueprint $table) {
    $table->id();
    $table->time('start_time');
    $table->time('end_time');
    $table->integer('sort_order')->default(0);
    $table->boolean('is_active')->default(true);
    $table->timestamps();

    $table->unique(['start_time', 'end_time']);
});

// master_slot_bookings (per master+slot+date)
Schema::create('master_slot_bookings', function (Blueprint $table) {
    $table->id();
    $table->foreignId('master_id')->constrained()->cascadeOnDelete();
    $table->foreignId('slot_id')->constrained()->cascadeOnDelete();
    $table->date('date');
    $table->enum('status', ['FREE', 'PENDING', 'RESERVED', 'BLOCKED'])->default('FREE');
    $table->unsignedBigInteger('order_id')->nullable();
    $table->string('block_reason')->nullable();
    $table->timestamps();

    $table->unique(['master_id', 'slot_id', 'date']);
});
```

---

### Service Layer (SlotService.php)

#### Get Weekly Calendar for Master
```php
public function getMasterWeeklyCalendar(Master $master, string $startDate): array
{
    $start = Carbon::parse($startDate)->startOfWeek();
    $slots = $this->slotRepository->getActive();
    $calendar = [];

    for ($i = 0; $i < 7; $i++) {
        $date = $start->copy()->addDays($i);
        $dateStr = $date->toDateString();

        // Get bookings for this master on this date
        $bookings = MasterSlotBooking::where('master_id', $master->id)
            ->whereDate('date', $dateStr)
            ->get()
            ->keyBy('slot_id');

        $daySlots = $slots->map(function ($slot) use ($bookings) {
            $booking = $bookings->get($slot->id);
            return [
                'slot_id' => $slot->id,
                'status' => $booking?->status ?? 'FREE',
                'booking_id' => $booking?->id,
                'block_reason' => $booking?->block_reason,
            ];
        })->toArray();

        $calendar[] = [
            'date' => $dateStr,
            'day_name' => $date->locale('uz')->dayName,
            'day_short' => mb_substr($date->locale('uz')->shortDayName, 0, 2),
            'day_number' => $date->day,
            'is_today' => $date->isToday(),
            'slots' => $daySlots,
        ];
    }

    return $calendar;
}
```

#### Block Single Slot
```php
public function blockSlot(Master $master, Slot $slot, string $date, ?string $reason = null): MasterSlotBooking
{
    $booking = MasterSlotBooking::where('master_id', $master->id)
        ->where('slot_id', $slot->id)
        ->where('date', $date)
        ->first();

    if ($booking && !in_array($booking->status, ['FREE', 'BLOCKED'])) {
        throw new \Exception('Cannot block a slot that is not free');
    }

    return MasterSlotBooking::updateOrCreate(
        [
            'master_id' => $master->id,
            'slot_id' => $slot->id,
            'date' => $date,
        ],
        [
            'status' => MasterSlotBooking::STATUS_BLOCKED,
            'block_reason' => $reason,
        ]
    );
}
```

#### Block Entire Day
```php
public function blockDay(Master $master, string $date, ?string $reason = null): void
{
    $slots = $this->slotRepository->getActive();

    foreach ($slots as $slot) {
        $booking = MasterSlotBooking::where('master_id', $master->id)
            ->where('slot_id', $slot->id)
            ->where('date', $date)
            ->first();

        // Only block if FREE or no booking exists
        if (!$booking || $booking->status === 'FREE') {
            MasterSlotBooking::updateOrCreate(
                [
                    'master_id' => $master->id,
                    'slot_id' => $slot->id,
                    'date' => $date,
                ],
                [
                    'status' => MasterSlotBooking::STATUS_BLOCKED,
                    'block_reason' => $reason,
                ]
            );
        }
    }
}
```

#### Unblock Slot
```php
public function unblockSlot(MasterSlotBooking $booking): void
{
    if ($booking->status !== MasterSlotBooking::STATUS_BLOCKED) {
        throw new \Exception('Slot is not blocked');
    }

    $booking->delete(); // Remove row = FREE status
}
```

---

### Controller Layer (MasterScheduleController.php)

```php
class MasterScheduleController extends Controller
{
    public function __construct(
        private readonly SlotService $slotService,
        private readonly SlotRepository $slotRepository,
    ) {}

    // Master selection page
    public function index()
    {
        return Inertia::render('Admin/Schedule/Index', [
            'masters' => Master::where('is_active', true)->get(),
        ]);
    }

    // Weekly calendar for specific master
    public function show(Master $master, Request $request)
    {
        $startDate = $request->get('start_date', now()->startOfWeek()->toDateString());

        return Inertia::render('Admin/Schedule/Show', [
            'master' => $master,
            'startDate' => $startDate,
            'calendar' => $this->slotService->getMasterWeeklyCalendar($master, $startDate),
            'slots' => $this->slotRepository->getActive(),
        ]);
    }

    // Block single slot
    public function blockSlot(Master $master, Request $request)
    {
        $request->validate([
            'slot_id' => 'required|exists:slots,id',
            'date' => 'required|date',
            'reason' => 'nullable|string|max:255',
        ]);

        $slot = Slot::findOrFail($request->slot_id);
        $this->slotService->blockSlot($master, $slot, $request->date, $request->reason);

        return back();
    }
}
```

---

### Vue Calendar Component (Schedule/Show.vue)

```vue
<template>
  <!-- Weekly navigation -->
  <div class="flex justify-between mb-4">
    <button @click="navigateWeek(-1)">← Oldingi hafta</button>
    <span>@@{{ calendar[0]?.date }} — @@{{ calendar[6]?.date }}</span>
    <button @click="navigateWeek(1)">Keyingi hafta →</button>
  </div>

  <!-- Calendar grid -->
  <table>
    <thead>
      <tr>
        <th>Vaqt</th>
        <th v-for="day in calendar" :key="day.date">
          @{{ day.day_short }}<br>@{{ day.day_number }}
        </th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="(slot, idx) in slots" :key="slot.id">
        <td>@{{ slot.start_time }} - @{{ slot.end_time }}</td>
        <td v-for="day in calendar" :key="day.date + slot.id">
          <div
            :class="getStatusClass(day.slots[idx]?.status)"
            @click="handleSlotClick(slot, day)"
          >
            @{{ getStatusLabel(day.slots[idx]?.status) }}
          </div>
        </td>
      </tr>
    </tbody>
  </table>
</template>

<script setup>
const getStatusClass = (status) => ({
  'FREE': 'bg-green-100 text-green-800',
  'PENDING': 'bg-yellow-100 text-yellow-800',
  'RESERVED': 'bg-blue-100 text-blue-800',
  'BLOCKED': 'bg-red-100 text-red-800',
}[status || 'FREE']);

const getStatusLabel = (status) => ({
  'FREE': "Bo'sh",
  'PENDING': 'Kutilmoqda',
  'RESERVED': 'Band',
  'BLOCKED': 'Yopiq',
}[status || 'FREE']);
</script>
```

---

### Admin Routes

```php
// routes/web.php
Route::middleware(['auth', 'role:admin|dispatcher'])->prefix('admin')->name('admin.')->group(function () {
    // Slot templates CRUD
    Route::resource('slots', SlotController::class)->except(['show']);
    Route::post('slots/generate-defaults', [SlotController::class, 'generateDefaults'])
        ->name('slots.generate-defaults');

    // Master schedule management
    Route::get('schedule', [MasterScheduleController::class, 'index'])->name('schedule.index');
    Route::get('schedule/{master}', [MasterScheduleController::class, 'show'])->name('schedule.show');
    Route::post('schedule/{master}/block-slot', [MasterScheduleController::class, 'blockSlot'])->name('schedule.block-slot');
    Route::post('schedule/{master}/unblock-slot', [MasterScheduleController::class, 'unblockSlot'])->name('schedule.unblock-slot');
    Route::post('schedule/{master}/block-day', [MasterScheduleController::class, 'blockDay'])->name('schedule.block-day');
    Route::post('schedule/{master}/unblock-day', [MasterScheduleController::class, 'unblockDay'])->name('schedule.unblock-day');
});
```

---

### Order Creation (Future Implementation)

When orders are implemented, the booking flow will:

```php
// OrderService.php
public function createOrder(array $data): Order
{
    return DB::transaction(function () use ($data) {
        $slot = Slot::findOrFail($data['slot_id']);
        $master = Master::findOrFail($data['master_id']);
        $date = $data['date'];

        // Check if slot is available
        $booking = MasterSlotBooking::where('master_id', $master->id)
            ->where('slot_id', $slot->id)
            ->where('date', $date)
            ->lockForUpdate()
            ->first();

        if ($booking && $booking->status !== 'FREE') {
            throw new SlotNotAvailableException('This slot is not available');
        }

        // Create order
        $order = Order::create([...]);

        // Mark slot as pending
        MasterSlotBooking::updateOrCreate(
            [
                'master_id' => $master->id,
                'slot_id' => $slot->id,
                'date' => $date,
            ],
            [
                'status' => MasterSlotBooking::STATUS_PENDING,
                'order_id' => $order->id,
            ]
        );

        return $order;
    });
}
```

---

### Configuration

```php
// config/booking.php
return [
    'session_duration' => env('SESSION_DURATION_MINUTES', 60),
    'session_gap' => env('SESSION_GAP_MINUTES', 30),
    'lead_time_hours' => env('BOOKING_LEAD_TIME_HOURS', 2),
    'pending_timeout_minutes' => env('PENDING_TIMEOUT_MINUTES', 30),
    'working_hours' => [
        'start' => env('WORKING_HOURS_START', '09:00'),
        'end' => env('WORKING_HOURS_END', '21:00'),
    ],
];
```

---

### Translations

```json
// uz.json
{
  "slots": {
    "title": "Vaqt Slotlari",
    "new": "Yangi Slot",
    "startTime": "Boshlanish vaqti",
    "endTime": "Tugash vaqti"
  },
  "schedule": {
    "title": "Jadval",
    "selectMaster": "Master tanlang",
    "free": "Bo'sh",
    "pending": "Kutilmoqda",
    "reserved": "Band",
    "blocked": "Yopiq",
    "blockSlot": "Slotni bloklash",
    "blockAll": "Barchasini bloklash"
  }
}
```
